### ISSUE TITLE
H5Cropper is not defined

### ISSUE THREAD

**Issue by rsq1259** [2277419213/vue-calendar-h5#1]
npm引入组件吼发现报了`H5Cropper is not defined`是不是误写了？

**Comment by 2277419213** [comment]
啊，这个影响使用嘛，因为npm框架是我在我之前项目copy过来改了部分内容，是引入报错还是？

**Comment by rsq1259** [comment]
引入之后会报错，建议修改一下

**Comment by 2277419213** [comment]
刚测试下，好像没有发现这种情况，可以的话加个WeChat交流下

**Comment by rsq1259** [comment]
可以，我ID就是微信号

**Comment by gyyxiaogao** [comment]
bug没有解决咋关了？
![image](https://user-images.githubusercontent.com/16957066/149288467-109bc3ba-8e13-4c2a-b8bd-14666daa5073.png)

**Comment by gyyxiaogao** [comment]
![image](https://user-images.githubusercontent.com/16957066/149288902-f7978c61-aa68-4458-90e8-b7d22fc539f5.png)
